<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>JennGllg.Fr.MonKado.Back.Tests.Common</AssemblyName>
    <RootNamespace>JennGllg.Fr.MonKado.Back.Tests.Common</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Application/Application.csproj" />
  </ItemGroup>

</Project>
