<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql</AssemblyName>
		<RootNamespace>JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Application\Application.csproj" />
	  <ProjectReference Include="..\Domain\Domain.csproj" />
	</ItemGroup>

</Project>
