<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>JennGllg.Fr.MonKado.Back.Worker</AssemblyName>
    <RootNamespace>JennGllg.Fr.MonKado.Back.Worker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" />
    <PackageReference Include="Google.Apis.Gmail.v1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="MimeKit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Infrastructure.Persistence.PostgreSql\Infrastructure.Persistence.PostgreSql.csproj" />
  </ItemGroup>

</Project>
