<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.UnitTests</AssemblyName>
		<RootNamespace>JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.UnitTests</RootNamespace>
		<IsPackable>false</IsPackable>
		<TestingPlatformDotnetTestSupport>false</TestingPlatformDotnetTestSupport>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit.v3" />
		<PackageReference Include="xunit.runner.visualstudio">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\Infrastructure.Persistence.PostgreSql\Infrastructure.Persistence.PostgreSql.csproj" />
	  <ProjectReference Include="..\Tests.Common\Tests.Common.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

</Project>
