using JennGllg.Fr.MonKado.Back.Application.Models;

namespace JennGllg.Fr.MonKado.Back.Application.Abstractions;

/// <summary>Coordinates purpose-bound second-factor proofs and transactional authenticator management.</summary>
public interface ITwoFactorService
{
    /// <summary>Verifies a live sign-in proof, begins recovery or creates a fully verified session.</summary>
    /// <param name="flow">The opaque sign-in proof.</param>
    /// <param name="code">The submitted TOTP code, when required by the current step.</param>
    /// <param name="recoveryCode">A recovery code that permits replacement only.</param>
    /// <param name="cancellationToken">The request cancellation token.</param>
    /// <returns>Confirmed tokens or a replacement challenge, never both.</returns>
    Task<TwoFactorCompletionResult> CompleteAsync(
        string flow,
        string? code,
        string? recoveryCode,
        CancellationToken cancellationToken);

    /// <summary>Creates or retrieves a candidate authenticator for an authorized enrollment or replacement.</summary>
    /// <param name="flow">The operation-bound proof.</param>
    /// <param name="cancellationToken">The request cancellation token.</param>
    /// <returns>The candidate manual key and enrollment URI.</returns>
    Task<TwoFactorSetupResponse> GetSetupAsync(
        string flow,
        CancellationToken cancellationToken);

    /// <summary>Confirms a candidate authenticator and returns newly generated recovery codes once.</summary>
    /// <param name="flow">The operation-bound proof.</param>
    /// <param name="code">A TOTP generated by the candidate authenticator.</param>
    /// <param name="cancellationToken">The request cancellation token.</param>
    /// <returns>New recovery codes after the credential change is confirmed.</returns>
    Task<TwoFactorRecoveryCodesResponse> ConfirmSetupAsync(
        string flow,
        string code,
        CancellationToken cancellationToken);

    /// <summary>Reads the current member's non-secret enrollment status.</summary>
    /// <param name="memberId">The authenticated member.</param>
    /// <param name="cancellationToken">The request cancellation token.</param>
    /// <returns>The enabled state and remaining recovery-code count.</returns>
    Task<TwoFactorStatusResponse> GetStatusAsync(
        Guid memberId,
        CancellationToken cancellationToken);

    /// <summary>Verifies the current factor before issuing an operation-bound management grant.</summary>
    /// <param name="memberId">The authenticated member.</param>
    /// <param name="accessTokenId">The registered token proving the calling session.</param>
    /// <param name="purpose">The requested management action.</param>
    /// <param name="code">The current authenticator code.</param>
    /// <param name="recoveryCode">A recovery code, accepted only for forced replacement.</param>
    /// <param name="cancellationToken">The request cancellation token.</param>
    /// <returns>A short-lived management grant.</returns>
    Task<TwoFactorChallengeResponse> ReauthenticateAsync(
        Guid memberId,
        Guid accessTokenId,
        TwoFactorFlowPurpose purpose,
        string? code,
        string? recoveryCode,
        CancellationToken cancellationToken);

    /// <summary>Consumes a regeneration grant, revokes existing sessions and replaces all recovery codes.</summary>
    /// <param name="flow">The grant bound exclusively to recovery-code regeneration.</param>
    /// <param name="cancellationToken">The request cancellation token.</param>
    /// <returns>The new recovery codes, only after a confirmed commit.</returns>
    Task<TwoFactorRecoveryCodesResponse> RegenerateRecoveryCodesAsync(
        string flow,
        CancellationToken cancellationToken);
}
