<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>JennGllg.Fr.MonKado.Back.Tools.GmailOAuthBootstrap.UnitTests</AssemblyName>
    <RootNamespace>JennGllg.Fr.MonKado.Back.Tools.GmailOAuthBootstrap.UnitTests</RootNamespace>
    <IsPackable>false</IsPackable>
    <TestingPlatformDotnetTestSupport>false</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Tools.GmailOAuthBootstrap/Tools.GmailOAuthBootstrap.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
