<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>JennGllg.Fr.MonKado.Back.Application</AssemblyName>
		<RootNamespace>JennGllg.Fr.MonKado.Back.Application</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain\Domain.csproj" />
	</ItemGroup>

</Project>
