<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<AssemblyName>JennGllg.Fr.MonKado.Back.Application</AssemblyName>
		<RootNamespace>JennGllg.Fr.MonKado.Back.Application</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>annotations</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain\Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Commands\" />
	  <Folder Include="Configurations\" />
	  <Folder Include="Models\Responses\" />
	  <Folder Include="MappingProfiles\" />
	  <Folder Include="Queries\" />
	  <Folder Include="Repositories\Abstractions\" />
	</ItemGroup>

</Project>
