// <auto-generated />
using System;
using JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Migrations
{
    [DbContext(typeof(MonKadoDbContext))]
    partial class MonKadoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.GiftReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WishId")
                        .HasColumnType("uuid")
                        .HasColumnName("wish_id");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_id");

                    b.Property<Guid>("WishlistParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_participant_id");

                    b.HasKey("Id")
                        .HasName("pk_gift_reservations");

                    b.HasIndex("WishlistId", "WishId")
                        .HasDatabaseName("ix_gift_reservations_wishlist_id_wish_id");

                    b.HasIndex("WishlistId", "WishlistParticipantId")
                        .HasDatabaseName("ix_gift_reservations_wishlist_id_wishlist_participant_id");

                    b.HasIndex("WishlistParticipantId", "WishId")
                        .IsUnique()
                        .HasDatabaseName("ux_gift_reservations_participant_wish");

                    b.ToTable("gift_reservations", "public", t =>
                        {
                            t.HasCheckConstraint("ck_gift_reservations_quantity_valid", "quantity BETWEEN 1 AND 100");

                            t.HasCheckConstraint("ck_gift_reservations_timestamps_consistent", "updated_at IS NULL OR updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.GiftReservationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("WishId")
                        .HasColumnType("uuid")
                        .HasColumnName("wish_id");

                    b.Property<string>("WishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("wish_name");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_id");

                    b.Property<string>("WishlistName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("wishlist_name");

                    b.HasKey("Id")
                        .HasName("pk_gift_reservation_histories");

                    b.HasIndex("MemberId", "LastActivityAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_gift_reservation_histories_member_activity");

                    b.HasIndex("MemberId", "Status", "LastActivityAt", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_gift_reservation_histories_member_status_activity");

                    b.ToTable("gift_reservation_histories", "public", t =>
                        {
                            t.HasCheckConstraint("ck_gift_reservation_histories_lifecycle_consistent", "last_activity_at >= created_at AND ((status = 'Active' AND ended_at IS NULL) OR (status IN ('Cancelled', 'Unavailable') AND ended_at = last_activity_at))");

                            t.HasCheckConstraint("ck_gift_reservation_histories_quantity_valid", "quantity BETWEEN 1 AND 100");

                            t.HasCheckConstraint("ck_gift_reservation_histories_status_valid", "status IN ('Active', 'Cancelled', 'Unavailable')");

                            t.HasCheckConstraint("ck_gift_reservation_histories_wish_name_valid", "char_length(btrim(wish_name)) > 0 AND wish_name !~ '[[:cntrl:]]'");

                            t.HasCheckConstraint("ck_gift_reservation_histories_wishlist_name_valid", "char_length(btrim(wishlist_name)) > 0 AND wishlist_name !~ '[[:cntrl:]]'");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.GuestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_guest_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_guest_sessions_expires_at");

                    b.ToTable("guest_sessions", "public", t =>
                        {
                            t.HasCheckConstraint("ck_guest_sessions_secret_hash_length", "octet_length(secret_hash) = 32");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.Wish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("ImageContentHash")
                        .HasColumnType("bytea")
                        .HasColumnName("image_content_hash");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<long>("Position")
                        .HasColumnType("bigint")
                        .HasColumnName("position");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_id");

                    b.HasKey("Id")
                        .HasName("pk_wishes");

                    b.HasAlternateKey("WishlistId", "Id")
                        .HasName("ak_wishes_wishlist_id_id");

                    b.HasIndex("ImageId")
                        .IsUnique()
                        .HasDatabaseName("ux_wishes_image_id")
                        .HasFilter("image_id IS NOT NULL");

                    b.HasIndex("WishlistId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_wishes_wishlist_position");

                    b.ToTable("wishes", "public", t =>
                        {
                            t.HasCheckConstraint("ck_wishes_image_fields_consistent", "(image_id IS NULL AND image_content_hash IS NULL) OR (image_id IS NOT NULL AND image_content_hash IS NOT NULL AND octet_length(image_content_hash) = 32)");

                            t.HasCheckConstraint("ck_wishes_name_valid", "char_length(btrim(name)) > 0 AND name !~ '[[:cntrl:]]'");

                            t.HasCheckConstraint("ck_wishes_position_valid", "position > 0");

                            t.HasCheckConstraint("ck_wishes_price_valid", "price IS NULL OR price > 0");

                            t.HasCheckConstraint("ck_wishes_quantity_valid", "quantity BETWEEN 1 AND 100");

                            t.HasCheckConstraint("ck_wishes_timestamps_consistent", "updated_at IS NULL OR updated_at >= created_at");

                            t.HasCheckConstraint("ck_wishes_url_valid", "url IS NULL OR (url ~* '^https?://[^[:space:]]+$' AND position('@' in split_part(split_part(split_part(url, '/', 3), '?', 1), '#', 1)) = 0)");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suspended");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("Occasion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("occasion");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("suspension_reason");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_wishlists");

                    b.HasIndex("OwnerId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_wishlists_owner_normalized_name");

                    b.ToTable("wishlists", "public", t =>
                        {
                            t.HasCheckConstraint("ck_wishlists_name_valid", "char_length(btrim(name)) > 0 AND name !~ '[[:cntrl:]]'");

                            t.HasCheckConstraint("ck_wishlists_occasion_valid", "occasion IN ('Birthday', 'Christmas', 'Wedding', 'Birth', 'Other')");

                            t.HasCheckConstraint("ck_wishlists_suspension_consistent", "(NOT is_suspended AND suspension_reason IS NULL AND suspended_at IS NULL) OR (is_suspended AND suspension_reason IS NOT NULL AND char_length(btrim(suspension_reason)) > 0 AND suspended_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_wishlists_timestamps_consistent", "updated_at IS NULL OR updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.WishlistModerationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<Guid?>("AdministratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("administrator_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_id");

                    b.HasKey("Id")
                        .HasName("pk_wishlist_moderation_events");

                    b.HasIndex("AdministratorId")
                        .HasDatabaseName("ix_wishlist_moderation_events_administrator_id");

                    b.HasIndex("OccurredAt", "Id")
                        .HasDatabaseName("ix_wishlist_moderation_events_occurred_at_id");

                    b.HasIndex("WishlistId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_wishlist_moderation_events_wishlist_id_sequence");

                    b.ToTable("wishlist_moderation_events", "public", t =>
                        {
                            t.HasCheckConstraint("ck_wishlist_moderation_events_action", "action IN ('Suspended', 'ReasonUpdated', 'Reactivated')");

                            t.HasCheckConstraint("ck_wishlist_moderation_events_reason", "(action = 'Reactivated' AND reason IS NULL) OR (action IN ('Suspended', 'ReasonUpdated') AND reason IS NOT NULL AND char_length(btrim(reason)) > 0)");

                            t.HasCheckConstraint("ck_wishlist_moderation_events_sequence", "sequence > 0");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.WishlistParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GuestDisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("guest_display_name");

                    b.Property<Guid?>("GuestSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_session_id");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_id");

                    b.HasKey("Id")
                        .HasName("pk_wishlist_participants");

                    b.HasAlternateKey("WishlistId", "Id")
                        .HasName("ak_wishlist_participants_wishlist_id_id");

                    b.HasIndex("GuestSessionId")
                        .HasDatabaseName("ix_wishlist_participants_guest_session_id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_wishlist_participants_member_id");

                    b.HasIndex("WishlistId", "GuestSessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_wishlist_participants_wishlist_guest_session")
                        .HasFilter("guest_session_id IS NOT NULL");

                    b.HasIndex("WishlistId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ux_wishlist_participants_wishlist_member")
                        .HasFilter("member_id IS NOT NULL");

                    b.ToTable("wishlist_participants", "public", t =>
                        {
                            t.HasCheckConstraint("ck_wishlist_participants_identity", "member_id IS NULL OR guest_session_id IS NULL");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.WishlistReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("details");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reason");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_note");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByAdministratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_administrator_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_id");

                    b.HasKey("Id")
                        .HasName("pk_wishlist_reports");

                    b.HasIndex("ReviewedByAdministratorId")
                        .HasDatabaseName("ix_wishlist_reports_reviewed_by_administrator_id");

                    b.HasIndex("WishlistId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_wishlist_reports_wishlist_id_created_at_id");

                    b.HasIndex("WishlistId", "Status", "CreatedAt", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_wishlist_reports_wishlist_id_status_created_at_id");

                    b.ToTable("wishlist_reports", "public", t =>
                        {
                            t.HasCheckConstraint("ck_wishlist_reports_reason_valid", "reason IN ('SpamOrScam', 'InappropriateContent', 'PrivacyViolation', 'Other')");

                            t.HasCheckConstraint("ck_wishlist_reports_review_consistent", "(reviewed_at IS NULL AND status = 'Pending' AND review_note IS NULL AND reviewed_by_administrator_id IS NULL) OR (reviewed_at IS NOT NULL AND reviewed_at >= created_at)");

                            t.HasCheckConstraint("ck_wishlist_reports_status", "status IN ('Pending', 'Upheld', 'Dismissed')");

                            t.HasCheckConstraint("ck_wishlist_reports_timestamps_consistent", "updated_at IS NULL OR updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.WishlistReportReviewEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdministratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("administrator_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("previous_status");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_wishlist_report_review_events");

                    b.HasIndex("AdministratorId")
                        .HasDatabaseName("ix_wishlist_report_review_events_administrator_id");

                    b.HasIndex("ReportId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_wishlist_report_review_events_report_id_sequence");

                    b.ToTable("wishlist_report_review_events", "public", t =>
                        {
                            t.HasCheckConstraint("ck_wishlist_report_review_events_sequence", "sequence > 0");

                            t.HasCheckConstraint("ck_wishlist_report_review_events_status", "status IN ('Pending', 'Upheld', 'Dismissed') AND previous_status IN ('Pending', 'Upheld', 'Dismissed')");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.WishlistShareLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ProtectedSecret")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("protected_secret");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash")
                        .IsFixedLength();

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_id");

                    b.HasKey("Id")
                        .HasName("pk_wishlist_share_links");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("ux_wishlist_share_links_secret_hash");

                    b.HasIndex("WishlistId")
                        .IsUnique()
                        .HasDatabaseName("ux_wishlist_share_links_wishlist_id");

                    b.ToTable("wishlist_share_links", "public", t =>
                        {
                            t.HasCheckConstraint("ck_wishlist_share_links_secret_hash_length", "octet_length(secret_hash) = 32");

                            t.HasCheckConstraint("ck_wishlist_share_links_timestamps_consistent", "updated_at IS NULL OR updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AccountErasureEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("ProtectedRecipient")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("protected_recipient");

                    b.HasKey("Id")
                        .HasName("pk_account_erasure_email_outbox");

                    b.HasIndex("AvailableAt", "Id")
                        .HasDatabaseName("ix_account_erasure_email_outbox_available_at_id");

                    b.HasIndex("ExpiresAt", "Id")
                        .HasDatabaseName("ix_account_erasure_email_outbox_expires_at_id");

                    b.ToTable("account_erasure_email_outbox", "public", t =>
                        {
                            t.HasCheckConstraint("ck_account_erasure_email_attempts", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_account_erasure_email_dates", "expires_at = created_at + interval '24 hours' AND available_at >= created_at");

                            t.HasCheckConstraint("ck_account_erasure_email_lease", "(lease_id IS NULL) = (locked_until IS NULL)");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AdministrativeAccountErasureEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdministratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("administrator_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("NotificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("notification_status");

                    b.Property<string>("RequestReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_reference");

                    b.HasKey("Id")
                        .HasName("pk_administrative_account_erasure_events");

                    b.HasIndex("AdministratorId")
                        .HasDatabaseName("ix_administrative_account_erasure_events_administrator_id");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_administrative_account_erasure_events_created_at_id");

                    b.ToTable("administrative_account_erasure_events", "public", t =>
                        {
                            t.HasCheckConstraint("ck_administrative_account_erasure_events_notification_status", "notification_status IN ('NotApplicable', 'Pending', 'Accepted', 'Failed')");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AdministrativeDataExportEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<Guid?>("AdministratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("administrator_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExportId")
                        .HasColumnType("uuid")
                        .HasColumnName("export_id");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("RequestReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_reference");

                    b.HasKey("Id")
                        .HasName("pk_administrative_data_export_events");

                    b.HasIndex("AdministratorId")
                        .HasDatabaseName("ix_administrative_data_export_events_administrator_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_administrative_data_export_events_created_at");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_administrative_data_export_events_created_at_id");

                    b.HasIndex("MemberId", "ExportId", "CreatedAt", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_administrative_data_export_events_member_id_export_id_creat");

                    b.ToTable("administrative_data_export_events", "public", t =>
                        {
                            t.HasCheckConstraint("ck_administrative_data_export_events_action", "action IN ('Requested', 'DownloadStarted')");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AdministrativeSessionRevocationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdministratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("administrator_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("RequestReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_reference");

                    b.HasKey("Id")
                        .HasName("pk_administrative_session_revocation_events");

                    b.HasIndex("AdministratorId")
                        .HasDatabaseName("ix_administrative_session_revocation_events_administrator_id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_administrative_session_revocation_events_member_id");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_administrative_session_revocation_events_created_at_id");

                    b.ToTable("administrative_session_revocation_events", "public");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AuthenticationAccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_authentication_access_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_authentication_access_tokens_expires_at");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_authentication_access_tokens_session_id");

                    b.ToTable("authentication_access_tokens", "public");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AuthenticationEmailOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<Guid?>("MemberAccountDeletionRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_account_deletion_request_id");

                    b.Property<Guid?>("MemberDataExportId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_data_export_id");

                    b.Property<Guid?>("MemberEmailChangeRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_email_change_request_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_message_id");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("recipient_email");

                    b.Property<string>("SecurityStampSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("security_stamp_snapshot");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_authentication_email_outbox");

                    b.HasIndex("MemberDataExportId")
                        .IsUnique()
                        .HasDatabaseName("ix_authentication_email_outbox_member_data_export_id")
                        .HasFilter("member_data_export_id IS NOT NULL");

                    b.HasIndex("MemberEmailChangeRequestId")
                        .HasDatabaseName("ix_authentication_email_outbox_member_email_change_request_id");

                    b.HasIndex("AvailableAt", "CreatedAt")
                        .HasDatabaseName("ix_authentication_email_outbox_pending_delivery")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("ProcessedAt", "Id")
                        .HasDatabaseName("ix_authentication_email_outbox_processed_cleanup")
                        .HasFilter("processed_at IS NOT NULL");

                    b.HasIndex("UserId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_authentication_email_outbox_pending_user_kind")
                        .HasFilter("processed_at IS NULL AND kind NOT IN ('PASSWORD_CHANGED_SECURITY_NOTIFICATION', 'PERSONAL_DATA_EXPORT_READY')");

                    b.HasIndex("UserId", "Kind", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_authentication_email_outbox_user_kind_created_at");

                    b.ToTable("authentication_email_outbox", "public", t =>
                        {
                            t.HasCheckConstraint("ck_authentication_email_outbox_attempt_count_non_negative", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_authentication_email_outbox_data_export_consistent", "(kind = 'PERSONAL_DATA_EXPORT_READY') = (member_data_export_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_authentication_email_outbox_deletion_request_consistent", "(kind = 'ACCOUNT_DELETION_CONFIRMATION') = (member_account_deletion_request_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_authentication_email_outbox_email_change_fields_consistent", "(kind IN ('EMAIL_CONFIRMATION', 'PERSONAL_DATA_EXPORT_READY') AND member_email_change_request_id IS NULL AND recipient_email IS NULL AND security_stamp_snapshot IS NULL) OR (kind = 'EMAIL_CHANGE_CONFIRMATION' AND member_email_change_request_id IS NOT NULL AND recipient_email IS NOT NULL AND security_stamp_snapshot IS NOT NULL) OR (kind = 'EMAIL_CHANGE_SECURITY_NOTIFICATION' AND member_email_change_request_id IS NOT NULL AND recipient_email IS NOT NULL AND security_stamp_snapshot IS NULL) OR (kind = 'PASSWORD_RESET' AND member_email_change_request_id IS NULL AND recipient_email IS NOT NULL AND security_stamp_snapshot IS NOT NULL) OR (kind = 'PASSWORD_CHANGED_SECURITY_NOTIFICATION' AND member_email_change_request_id IS NULL AND recipient_email IS NOT NULL AND security_stamp_snapshot IS NULL) OR (kind = 'ACCOUNT_DELETION_CONFIRMATION' AND member_email_change_request_id IS NULL AND recipient_email IS NOT NULL AND security_stamp_snapshot IS NOT NULL)");

                            t.HasCheckConstraint("ck_authentication_email_outbox_kind_valid", "kind IN ('EMAIL_CONFIRMATION', 'EMAIL_CHANGE_CONFIRMATION', 'EMAIL_CHANGE_SECURITY_NOTIFICATION', 'PASSWORD_RESET', 'PASSWORD_CHANGED_SECURITY_NOTIFICATION', 'ACCOUNT_DELETION_CONFIRMATION', 'PERSONAL_DATA_EXPORT_READY')");

                            t.HasCheckConstraint("ck_authentication_email_outbox_timestamps_consistent", "available_at >= created_at AND (processed_at IS NULL OR processed_at >= created_at)");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AuthenticationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsPersistent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_persistent");

                    b.Property<byte[]>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTime>("RenewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("renewed_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_authentication_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_authentication_sessions_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_authentication_sessions_user_id");

                    b.ToTable("authentication_sessions", "public", t =>
                        {
                            t.HasCheckConstraint("ck_authentication_sessions_refresh_token_hash_length", "octet_length(refresh_token_hash) = 32");

                            t.HasCheckConstraint("ck_authentication_sessions_timestamps_consistent", "renewed_at >= created_at AND expires_at > created_at AND expires_at >= renewed_at AND (revoked_at IS NULL OR revoked_at >= created_at)");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.GiftImageDeletionOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.HasKey("Id")
                        .HasName("pk_gift_image_deletion_outbox");

                    b.HasIndex("ImageId")
                        .IsUnique()
                        .HasDatabaseName("ux_gift_image_deletion_outbox_image_id");

                    b.HasIndex("AvailableAt", "CreatedAt")
                        .HasDatabaseName("ix_gift_image_deletion_outbox_available");

                    b.ToTable("gift_image_deletion_outbox", "public", t =>
                        {
                            t.HasCheckConstraint("ck_gift_image_deletion_outbox_attempt_count_non_negative", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_gift_image_deletion_outbox_timestamps_consistent", "available_at >= created_at");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MemberAccountDeletionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("security_stamp");

                    b.HasKey("Id")
                        .HasName("pk_member_account_deletion_requests");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_member_account_deletion_requests_expires_at");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_member_account_deletion_requests_member_id");

                    b.ToTable("member_account_deletion_requests", "public", t =>
                        {
                            t.HasCheckConstraint("ck_member_account_deletion_requests_expiration", "expires_at > created_at");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MemberDataExport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArchiveId")
                        .HasColumnType("uuid")
                        .HasColumnName("archive_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Failure")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("failure");

                    b.Property<DateTime?>("FilesCleanedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("files_cleaned_at");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTime?>("ReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_at");

                    b.Property<long?>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<DateTime?>("SnapshotAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_member_data_exports");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_member_data_exports_expires_at")
                        .HasFilter("status = 'Ready'");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasDatabaseName("ux_member_data_exports_active_member")
                        .HasFilter("member_id IS NOT NULL AND status IN ('Queued', 'Processing', 'Ready')");

                    b.HasIndex("AvailableAt", "CreatedAt", "Id")
                        .HasDatabaseName("ix_member_data_exports_available_at_created_at_id")
                        .HasFilter("status IN ('Queued', 'Processing')");

                    b.HasIndex("MemberId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_member_data_exports_member_id_created_at_id");

                    b.ToTable("member_data_exports", "public", t =>
                        {
                            t.HasCheckConstraint("ck_member_data_exports_archive", "(status IN ('Ready', 'Expired') AND archive_id IS NOT NULL AND snapshot_at IS NOT NULL AND ready_at IS NOT NULL AND expires_at IS NOT NULL AND size_in_bytes IS NOT NULL) OR (status NOT IN ('Ready', 'Expired') AND archive_id IS NULL AND snapshot_at IS NULL AND ready_at IS NULL AND expires_at IS NULL AND size_in_bytes IS NULL)");

                            t.HasCheckConstraint("ck_member_data_exports_attempts", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_member_data_exports_dates", "available_at >= created_at AND (expires_at IS NULL OR expires_at > ready_at) AND (size_in_bytes IS NULL OR size_in_bytes > 0)");

                            t.HasCheckConstraint("ck_member_data_exports_failure", "(status = 'Failed' AND failure IS NOT NULL AND failure IN ('GenerationFailed', 'TooLarge')) OR (status <> 'Failed' AND failure IS NULL)");

                            t.HasCheckConstraint("ck_member_data_exports_lease", "(status = 'Processing' AND lease_id IS NOT NULL AND locked_until IS NOT NULL) OR (status <> 'Processing' AND lease_id IS NULL AND locked_until IS NULL)");

                            t.HasCheckConstraint("ck_member_data_exports_status", "status IN ('Queued', 'Processing', 'Ready', 'Failed', 'Expired')");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MemberEmailChangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("current_email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("NewEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("new_email");

                    b.Property<string>("NormalizedNewEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_new_email");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_member_email_change_requests");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_member_email_change_requests_expires_at");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_member_email_change_requests_active_user")
                        .HasFilter("confirmed_at IS NULL AND revoked_at IS NULL");

                    b.ToTable("member_email_change_requests", "public", t =>
                        {
                            t.HasCheckConstraint("ck_member_email_change_requests_emails_different", "current_email <> new_email");

                            t.HasCheckConstraint("ck_member_email_change_requests_timestamps_consistent", "expires_at > created_at AND (confirmed_at IS NULL OR confirmed_at >= created_at) AND (revoked_at IS NULL OR revoked_at >= created_at) AND NOT (confirmed_at IS NOT NULL AND revoked_at IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<byte[]>("ProfileImageHash")
                        .HasColumnType("bytea")
                        .HasColumnName("profile_image_hash");

                    b.Property<Guid?>("ProfileImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_image_id");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime?>("UnconfirmedAccountExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unconfirmed_account_expires_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("user_name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_user_name");

                    b.HasIndex("ProfileImageId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_profile_image_id")
                        .HasFilter("profile_image_id IS NOT NULL");

                    b.HasIndex("UnconfirmedAccountExpiresAt")
                        .HasDatabaseName("ix_users_unconfirmed_account_expiry")
                        .HasFilter("email_confirmed = FALSE AND unconfirmed_account_expires_at IS NOT NULL");

                    b.ToTable("users", "public", t =>
                        {
                            t.HasCheckConstraint("ck_users_display_name_valid", "char_length(btrim(display_name)) > 0 AND display_name !~ '[[:cntrl:]]'");

                            t.HasCheckConstraint("ck_users_profile_image_consistent", "(profile_image_id IS NULL AND profile_image_hash IS NULL) OR (profile_image_id IS NOT NULL AND profile_image_hash IS NOT NULL AND octet_length(profile_image_hash) = 32)");

                            t.HasCheckConstraint("ck_users_timestamps_consistent", "updated_at >= created_at AND (unconfirmed_account_expires_at IS NULL OR unconfirmed_account_expires_at >= created_at)");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.WishPositionSequence", b =>
                {
                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_id");

                    b.Property<int>("CurrentCount")
                        .HasColumnType("integer")
                        .HasColumnName("current_count");

                    b.Property<long>("NextPosition")
                        .HasColumnType("bigint")
                        .HasColumnName("next_position");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("WishlistId")
                        .HasName("pk_wish_position_sequences");

                    b.ToTable("wish_position_sequences", "public", t =>
                        {
                            t.HasCheckConstraint("ck_wish_position_sequences_current_count_valid", "current_count >= 0 AND current_count <= 1000");

                            t.HasCheckConstraint("ck_wish_position_sequences_next_position_valid", "next_position >= 0");
                        });
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.WishlistModerationEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_error");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id")
                        .HasName("pk_wishlist_moderation_email_outbox");

                    b.HasIndex("AvailableAt", "Id")
                        .HasDatabaseName("ix_wishlist_moderation_email_outbox_available_at_id")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("ProcessedAt", "Id")
                        .HasDatabaseName("ix_wishlist_moderation_email_outbox_processed_at_id")
                        .HasFilter("processed_at IS NOT NULL");

                    b.ToTable("wishlist_moderation_email_outbox", "public", t =>
                        {
                            t.HasCheckConstraint("ck_wishlist_moderation_email_attempts", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_wishlist_moderation_email_dates", "available_at >= created_at AND (processed_at IS NULL OR processed_at >= created_at)");

                            t.HasCheckConstraint("ck_wishlist_moderation_email_lease", "(lease_id IS NULL) = (locked_until IS NULL)");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_normalized_name");

                    b.ToTable("roles", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019ec170-1570-7000-8000-000000000001"),
                            ConcurrencyStamp = "019ec170-1570-7000-8000-000000000002",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("0198d027-51c0-7000-8000-000000000002"),
                            ConcurrencyStamp = "0198d027-51c0-7000-8000-000000000003",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId", "LoginProvider")
                        .IsUnique()
                        .HasDatabaseName("ux_user_logins_user_id_login_provider");

                    b.ToTable("user_logins", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", "public");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.GiftReservation", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Domain.Entities.Wish", null)
                        .WithMany()
                        .HasForeignKey("WishlistId", "WishId")
                        .HasPrincipalKey("WishlistId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gift_reservations_wishes_wishlist_id_wish_id");

                    b.HasOne("JennGllg.Fr.MonKado.Back.Domain.Entities.WishlistParticipant", null)
                        .WithMany()
                        .HasForeignKey("WishlistId", "WishlistParticipantId")
                        .HasPrincipalKey("WishlistId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gift_reservations_participants_wishlist_id_participant_id");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.GiftReservationHistory", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gift_reservation_histories_users_member_id");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.Wish", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Domain.Entities.Wishlist", null)
                        .WithMany()
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishes_wishlists_wishlist_id");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.Wishlist", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishlists_users_owner_id");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.WishlistModerationEvent", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_wishlist_moderation_events_users_administrator_id");

                    b.HasOne("JennGllg.Fr.MonKado.Back.Domain.Entities.Wishlist", null)
                        .WithMany()
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishlist_moderation_events_wishlists_wishlist_id");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.WishlistParticipant", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Domain.Entities.GuestSession", null)
                        .WithMany()
                        .HasForeignKey("GuestSessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_wishlist_participants_guest_sessions_guest_session_id");

                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_wishlist_participants_users_member_id");

                    b.HasOne("JennGllg.Fr.MonKado.Back.Domain.Entities.Wishlist", null)
                        .WithMany()
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishlist_participants_wishlists_wishlist_id");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.WishlistReport", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByAdministratorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_wishlist_reports_users_reviewed_by_administrator_id");

                    b.HasOne("JennGllg.Fr.MonKado.Back.Domain.Entities.Wishlist", null)
                        .WithMany()
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishlist_reports_wishlists_wishlist_id");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.WishlistReportReviewEvent", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_wishlist_report_review_events_users_administrator_id");

                    b.HasOne("JennGllg.Fr.MonKado.Back.Domain.Entities.WishlistReport", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishlist_report_review_events_wishlist_reports_report_id");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Domain.Entities.WishlistShareLink", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Domain.Entities.Wishlist", null)
                        .WithOne()
                        .HasForeignKey("JennGllg.Fr.MonKado.Back.Domain.Entities.WishlistShareLink", "WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishlist_share_links_wishlists_wishlist_id");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AccountErasureEmail", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AdministrativeAccountErasureEvent", null)
                        .WithOne()
                        .HasForeignKey("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AccountErasureEmail", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_erasure_email_outbox_administrative_account_erasure");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AdministrativeAccountErasureEvent", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_administrative_account_erasure_events_asp_net_users_administr");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AdministrativeDataExportEvent", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_administrative_data_export_events_asp_net_users_administrator");

                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_administrative_data_export_events_asp_net_users_member_id");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AdministrativeSessionRevocationEvent", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_administrative_session_revocation_events_asp_net_users_admini");

                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_administrative_session_revocation_events_asp_net_users_member");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AuthenticationAccessToken", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AuthenticationSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_authentication_access_tokens_authentication_sessions_sessio");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AuthenticationEmailOutboxMessage", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MemberDataExport", null)
                        .WithMany()
                        .HasForeignKey("MemberDataExportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_authentication_email_outbox_member_data_exports_member_data");

                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MemberEmailChangeRequest", null)
                        .WithMany()
                        .HasForeignKey("MemberEmailChangeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_authentication_email_outbox_member_email_change_request_id");

                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_authentication_email_outbox_users_user_id");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.AuthenticationSession", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_authentication_sessions_users_user_id");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MemberAccountDeletionRequest", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_account_deletion_requests_asp_net_users_member_id");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MemberDataExport", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_member_data_exports_asp_net_users_member_id");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MemberEmailChangeRequest", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_email_change_requests_users_user_id");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.WishPositionSequence", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Domain.Entities.Wishlist", null)
                        .WithOne()
                        .HasForeignKey("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.WishPositionSequence", "WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wish_position_sequences_wishlists_wishlist_id");
                });

            modelBuilder.Entity("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.WishlistModerationEmail", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Domain.Entities.WishlistModerationEvent", null)
                        .WithOne()
                        .HasForeignKey("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.WishlistModerationEmail", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishlist_moderation_email_outbox_wishlist_moderation_events");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("JennGllg.Fr.MonKado.Back.Infrastructure.Persistence.PostgreSql.Entities.MonKadoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
